server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /vagas {
        try_files /vagas.html =404;
    }

    location = /admin {
        try_files /admin.html =404;
    }

    location = /login {
        try_files /login.html =404;
    }

    location = /candidato {
        try_files /candidato.html =404;
    }

    location = /admissao {
        try_files /admissao.html =404;
    }

    location = /candidatura {
        try_files /candidatura.html =404;
    }

    location = /avaliacao {
        try_files /avaliacao.html =404;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
